accounts/urls.py
# imports
from django.urls import path
from django.contrib.auth import views as auth_views

from . import forms
from . import views
# End: imports -----------------------------------------------------------------

app_name = 'accounts'  # Necessary for url naming. eg {% url 'accounts:signin' %}

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    # path('login/', views.LoginView.as_view(), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login2.html', form_class=forms.CustomAuthenticationForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('profile/', views.ProfileView.as_view(), name='view_profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('profile/delete/', views.DeleteUserView.as_view(), name='delete_user'),
]

root/urls.py
# imports
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

import debug_toolbar
# End: imports -----------------------------------------------------------------

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
]

urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

accounts/models.py
# imports
import typing

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth import models as auth_models
from django.contrib.auth.models import Group

if typing.TYPE_CHECKING:
    pass
# End: imports -----------------------------------------------------------------


class User(auth_models.User):

    class Gender(models.TextChoices):
        MALE = 'M', 'Male'
        FEMALE = 'F', 'Female'
        OTHER = 'O', 'Other'

    # department = models.ForeignKey('accounts.Department', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Avdeling', related_name='users')
    # nickname = models.CharField(max_length=150, unique=True, null=True, blank=False, verbose_name='Kallenavn')
    gender = models.CharField(max_length=1, choices=Gender.choices, default=None, null=True, blank=True, verbose_name='Kjønn')
    phone_number = models.CharField(max_length=13, default=None, null=True, blank=True, verbose_name='Mobilnummer')

    class Meta:
        ordering = ['username']

    def __str__(self):
        return f'{self.get_full_name() or self.username or self.email or self.id}'


class PermissionCode(models.Model):
    """ Secret code that users can submit to join groups. """
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=False, blank=False)
    secret = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return f'PermissionCode ({self.group}:{self.secret})'


class Department(models.Model):
    """
    Like Group, but with no permissions.

    Can be used for visual affiliations.
    Supports hierarchical departments.
    """
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Navn')
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children', verbose_name='Over-seksjon')
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through='accounts.DepartmentMembership', related_name='departments', verbose_name='Medlemmer')

    class Meta:
        ordering = []
        verbose_name = 'Seksjon'
        verbose_name_plural = 'Seksjoner'

    def __str__(self):
        return f'{self.name}'

    def root_path(self, path=None):
        path = path or []
        path.append(self)
        if self.parent:
            return self.parent.root_path(path)
        return path

    def member_count(self):
        return self.members.all().count()


class DepartmentMembership(models.Model):
    """ Intermediate model: User <-> Department """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=False, verbose_name='Bruker')
    department = models.ForeignKey('accounts.Department', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Seksjon')
    date_joined = models.DateTimeField(default=timezone.now, null=False, blank=False, verbose_name='Dato innmeldt')

    class Meta:
        ordering = ['id']
        verbose_name = 'Medlem'
        verbose_name_plural = 'Medlemmer'

    def __str__(self):
        return f'Medlem: {self.user}'

accounts/forms.py
# imports
import typing

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm

User = get_user_model()

if typing.TYPE_CHECKING:
    from django.http import HttpRequest

# End: imports -----------------------------------------------------------------


class SignUpForm(UserCreationForm):

    required_css_class = 'required font-bold'
    code = forms.CharField(required=False, label='Kode')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'phone_number',
            'gender',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        self.fields['password1'].help_text = "Your password can't be too similar to your other personal information. \
        Your password must contain at least 8 characters. \
        Your password can't be a commonly used password nor entierly numeric."


class EditUserForm(forms.ModelForm):

    required_css_class = 'required font-bold'

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'phone_number',
            'gender',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class CustomAuthenticationForm(AuthenticationForm):
    """ AuthenticationForm compatible with Bootstrap. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class CustomPasswordChangeForm(PasswordChangeForm):

    class Meta:
        model = User
        exclude = []
        labels = {
            'old_password': 'Gammelt passord',
            'new_password1': 'Nytt passord',
            'new_password2': 'Nytt passord bekreftelse',
        }

    def __init__(self, *args, **kwargs):
        request: HttpRequest = kwargs.pop('request')
        super().__init__(request.user, *args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

accounts/views.py
# imports
from django.views import View
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from accounts import forms as account_forms
from accounts import models as account_models

User = get_user_model()

# End: imports -----------------------------------------------------------------


@method_decorator([login_required], name='dispatch')
class ProfileView(View):
    template = 'accounts/profile.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template, {})


@method_decorator([login_required], name='dispatch')
class EditProfileView(View):
    template = 'accounts/edit_profile.html'
    form_class = account_forms.EditUserForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=request.user)
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profilen din har blitt oppdatert')
            return redirect('accounts:profile')
        return render(request, self.template, {'form': form})


class SignUpView(View):
    template = 'accounts/registration_form.html'
    form_class = account_forms.SignUpForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            try:
                code = form.cleaned_data['code']
                group = account_models.PermissionCode.objects.get(secret=code).group
                user.groups.add(group)
                messages.success(request, f'Med koden "{code}" har du blitt lagt til i avdeling: {group.name}')
            except:  # pylint: disable=bare-except
                messages.warning(request, f'Koden "{code}" tilsvarer ingen avdeling. Ta kontakt med admin')

            return redirect('home')
        return render(request, self.template, {'form': form})


@method_decorator([login_required], name='dispatch')
class DeleteUserView(View):

    def delete(self, request, *args, **kwargs):
        request.user.delete()
        logout(request)
        messages.success(request, 'Brukeren din har blitt slettet fra systemet')
        return redirect('home')


class LoginView(View):
    template = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template)

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        error = None
        if user is not None:
            login(request, user)
            return redirect('accounts:profile')
        error = 'Feil'

        return render(request, self.template, {'error': error})


@method_decorator([login_required], name='dispatch')
class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('accounts:login')


@method_decorator([login_required], name='dispatch')
class ChangePasswordView(View):
    template = 'accounts/change_password.html'
    form_class = account_forms.CustomPasswordChangeForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(request=request)
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, request=request)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return redirect('accounts:profile')
        return render(request, self.template, {'form': form})

accounts/templates/accounts/change_password.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{ request.user }}{% endblock title %}

{% block head %}
    <style media="screen">
        #form {
            max-width: 35em;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'accounts:change_password' %}">Bytt passord</a></li>
{% endblock %}

{% block body %}
    <div id="form">
        <h1>Bytt passord:</h1>
        <form class="container default-theme user-theme" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-block btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

{% block scriptblock %}
    <script type="text/javascript">
        $(document).ready(function() {

        })
    </script>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{ request.user }}{% endblock title %}

{% block head %}
    <style media="screen">
        #form {
            max-width: 35em;
        }
    </style>
{% endblock head %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'accounts:edit_profile' %}">Rediger profil</a></li>
{% endblock %}

{% block body %}
    <div id="form" class="default-theme user-theme">
        <h1>Rediger profil:</h1>
        <!-- Edit user (form) -->
        <form method="POST"> <!-- Bootstrap -->
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group"> <!-- Bootstrap -->
                    {{ field.label_tag }}
                    {{ field }}
                    <div class="text-muted small">
                        {{ field.help_text }}
                    </div>
                    {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}

            <div class="row">
                <div class="col-sm-4 mt-2">
                    <a class="btn btn-secondary btn-block text-light" href="{% url 'accounts:profile' %}">Avbryt</a>
                </div>
                <div class="col mt-2">
                    <button type="submit" class="btn btn-primary btn-block text-light">Lagre</button>
                </div>
            </div>


        </form> <!-- End: Edit user (form) -->


    </div>

    <br><br><br> <!-- Quickfix footer -->
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Logg inn{% endblock title %}

{% block head %}
    <style media="screen">
        .default-theme {
            min-width: 220px;
            max-width: 500px;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:login' %}">Logg inn</a></li>
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h2>Du er allerede logget inn</h2>
    {% else %}
        <div class="row">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                <div class="default-theme">

                    <h2>Logg inn:</h2>

                    <form class="" method="post">
                        {% csrf_token %}
                        Email:<br>
                        <input class="form-control mb-3" type="text" name="email" value="">
                        Passord:<br>
                        <input class="form-control mb-3" type="password" name="password" value="">

                        <button class="btn btn-primary mt-3" type="submit" name="button">Logg inn</button>
                    </form>

                    <div class="text-danger">
                        {{ error }}
                    </div>

                    <div class="mt-3">Mangler du bruker? <a href="{% url 'accounts:signup' %}">Opprett en her</a></div>


                </div>

        </div>
        <div class="col-sm">

        </div>
      </div>

    {% endif %}
{% endblock %}

{% block scriptblock %}
    <script type="text/javascript">
        $(document).ready(function() {

        })
    </script>
{% endblock %}

accounts/templates/accounts/login2.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Logg inn{% endblock title %}

{% block head %}
    <style media="screen">
        .default-theme {
            min-width: 220px;
            max-width: 500px;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:login' %}">Logg inn</a></li>
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h2>Du er allerede logget inn</h2>
    {% else %}
        <div class="row">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                <div class="default-theme">

                    <h2>Logg inn:</h2>

                    <form class="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {{ field.label_tag }}
                            {{ field }}
                            {% for error in field.errors %}
                                <div class="text-danger">
                                    {{ error }}
                                </div>
                            {% endfor %}

                        {% endfor %}

                        {% for error in form.non_field_errors %}
                            <div class="text-danger">
                                {{ error }}
                            </div>
                        {% endfor %}

                        <button class="btn btn-primary mt-3" type="submit" name="button">Logg inn</button>
                    </form>

                    <div class="text-danger">
                        {{ error }}
                    </div>

                    <div class="mt-3">Mangler du bruker? <a href="{% url 'accounts:signup' %}">Opprett en her</a></div>


                </div>

        </div>
        <div class="col-sm">

        </div>
      </div>

    {% endif %}
{% endblock %}

{% block scriptblock %}
    <script type="text/javascript">
        $(document).ready(function() {

        })
    </script>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{ request.user }}{% endblock %}

{% block head %}
    <style media="screen">

    #panels {
        max-height: 100%;
        overflow-y: auto;
    }

    #panels {
        overflow-y: auto;
        max-height: 40vh;

    }


    </style>
{% endblock head %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
{% endblock %}

{% block body %}
<div class="">

    <div class="h1 text-center">
        {{ user }}
    </div>

    <div class="row mt-2">

        <div class="col-md mt-2 border rounded-xl">
            <div class="h1">
                Eksempel
            </div>
        </div>

        <div class="col-md-6 mt-2">
            <div class="">
                <div class="h4">
                    Personlig informasjon:
                </div>
                <div class="">
                    <div>Fullt navn: {{ user.get_full_name | default:'Ikke oppgitt' }}</div>
                    <div>Email: {{ user.email }}</div>
                    <div>Kallenavn: {{ user.nickname }}</div>
                </div>
                <div class="text-left mt-4">
                    <a class="btn btn-secondary text-light" href="{% url 'accounts:edit_profile' %}">Rediger profil</a>
                    <a class="btn btn-secondary text-light" href="{% url 'accounts:change_password' %}">Endre passord</a>
                    <a class="btn btn-danger text-light" href="{% url 'accounts:logout' %}">Logg ut</a>
                </div>
            </div>
        </div>
    </div>






</div>
{% endblock %}

accounts/templates/accounts/registration_form.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Opprett bruker{% endblock %}

{% block head %}
    <style>
        #table-column {
            min-width: 250px;
            max-width: 600px;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:signup' %}">Registrering</a></li>
{% endblock %}

{% block body %}
    <div class="">

        <div class="row">
            <div class="col-sm">

            </div>
            <div id="table-column" class="col-auto">
                <h2>Lag bruker</h2>

                <form class="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="text-secondary">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </p>
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                    <button type="submit" class="btn btn-lg btn-primary btn-block">Opprett bruker</button>
                </form>
                <br>

                <span>Har du allerede en bruker?</span>
                <a href="{% url 'accounts:login' %}">Logg inn her</a>
            </div>
            <div class="col-sm">

            </div>
        </div>

    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $(function () {
                $('[data-toggle="popover"]').popover()
            })
        })
    </script>
{% endblock %}