accounts/urls.py
# imports
from django.urls import path
from django.contrib.auth import views as auth_views

from . import forms
from . import views
# End: imports -----------------------------------------------------------------

app_name = 'accounts'  # Necessary for url naming. eg {% url 'accounts:signin' %}

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    # path('login/', views.LoginView.as_view(), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login2.html', form_class=forms.CustomAuthenticationForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('profile/', views.ProfileView.as_view(), name='view_profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('profile/delete/', views.DeleteUserView.as_view(), name='delete_user'),
]

root/management/commands/app_skeleton/urls.py
# imports
from django.urls import path

from . import views
# End: imports -----------------------------------------------------------------

app_name = 'app_skeleton'  # Necessary for url naming. eg {% url 'app_skeleton:view_profile' %}

urlpatterns = [
    path('example/<int:example_id>/', views.ExampleView.as_view(), name='view_profile'),
]

root/urls.py
# imports
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

import debug_toolbar
# End: imports -----------------------------------------------------------------

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
]

urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

root/management/commands/app_skeleton/models.py
# imports
import typing

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth import models as auth_models
from django.contrib.auth import get_user_model

from django.contrib.auth.models import Group

from root import models as root_models

User = get_user_model()

if typing.TYPE_CHECKING:
    pass
# End: imports -----------------------------------------------------------------


class SomeMixin():
    """ Get something """

    def get_some(self, thing: dict[str, int]) -> int:
        print(f'Getting something as {str(self)}')
        return thing.get('some')


class Example(SomeMixin, root_models.CustomBaseModel):

    class Kind(models.TextChoices):
        SOME = 'S', 'Some'
        THING = 'T', 'Thing'

    kind = models.CharField(max_length=1, choices=Kind.choices, default=None, null=True, blank=True, verbose_name='kind')
    some = models.CharField(max_length=13, default=None, null=True, blank=True, verbose_name='Some')
    thing = models.CharField(max_length=13, default=None, null=True, blank=True, verbose_name='Thing')
    groups = models.ManyToManyField(to=Group, through='GroupMembership')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=False, related_name='examples')

    class Meta:
        ordering = ['some', 'thing']
        verbose_name = 'Example'
        verbose_name_plural = 'Examples'

    def __str__(self):
        return f'Example: {self.id}'


class GroupMembership(models.Model):
    """ Intermediate model: Example <-> Group """
    example = models.ForeignKey(Example, on_delete=models.CASCADE, null=False, blank=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=False, blank=False)
    date_joined = models.DateTimeField(default=timezone.now, null=False, blank=False)

    class Meta:
        ordering = ['date_joined']

    def __str__(self):
        return f'Membership: {self.user} {str(self.group)}'

root/models/base.py
# imports
from django import forms
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth import models as auth_models

# End: imports -----------------------------------------------------------------

# https://github.com/django/django/blob/master/django/forms/models.py


class CustomModelForm(forms.ModelForm):

    def save(self, *args, commit=True, **kwargs):  # pylint: disable=arguments-differ
        """
        Override django ModelForm.save() to implement kwargs. Do not use super() in this class!
        Changes: user arg is added

        Source __doc__:
        Save this form's self.instance object if commit=True. Otherwise, add
        a save_m2m() method to the form which can be called after the instance
        is saved manually at a later time. Return the model instance.
        """
        if self.errors:
            raise ValueError(
                "The %s could not be %s because the data didn't validate." % ( # pylint: disable=consider-using-f-string
                    self.instance._meta.object_name,
                    'created' if self.instance._state.adding else 'changed',  # pylint: disable=protected-access
                )
            )  # pylint: disable=consider-using-f-string
        if commit:
            # If committing, save the instance and the m2m data immediately.
            self.instance.save(*args, **kwargs)  # <--- This is the only difference
            self._save_m2m()
        else:
            # If not committing, add a method to the form to allow deferred
            # saving of m2m data.
            self.save_m2m = self._save_m2m  # pylint: disable=attribute-defined-outside-init
        return self.instance


class CustomBaseAdmin(admin.ModelAdmin):
    readonly_fields = ['creator', 'created', 'last_edited', 'last_editor']

    # list_display = []
    # ordering = []
    # list_filter = []
    # filter_horizontal = []
    # search_fields = []

    def save_model(self, request, obj, form, change):
        try:
            if not change:
                obj.creator = request.user
                obj.created = timezone.now()
            obj.last_editor = request.user
            obj.last_edited = timezone.now()
        except Exception as _:  # pylint: disable=broad-except
            pass

        return super().save_model(request, obj, form, change)


class CustomBaseModel(models.Model):
    last_editor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        editable=False,
        related_name='editor_%(class)s_set',
        verbose_name='Sist redigert av'
    )
    last_edited = models.DateTimeField(null=True, blank=True, editable=False, verbose_name='Sist redigert')
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        editable=False,
        related_name='creator_%(class)s_set',
        verbose_name='Opprettet av'
    )
    created = models.DateTimeField(null=True, blank=True, editable=False, verbose_name='Opprettet')

    class Meta:
        abstract = True

    def is_edited(self):
        return self.created != self.last_edited

    def clean(self, *args, **kwargs):
        pass

    def save(self, *args, **kwargs):
        self.clean()
        user = kwargs.pop('user', None)  # Must pop because super().save() doesn't accept user
        if isinstance(user, auth_models.AnonymousUser):
            user = None  # creator and last_editor can't be AnonymousUser
        if not self.id:
            self.created = timezone.now()
            if user:
                self.creator = user
        self.last_edited = timezone.now()
        if user:
            self.last_editor = user

        super().save(*args, **kwargs)

root/management/commands/app_skeleton/forms.py
# imports
from django import forms
from django.contrib.auth import get_user_model

from . import models

User = get_user_model()
# End: imports -----------------------------------------------------------------


class ExampleForm(forms.ModelForm):

    required_css_class = 'required font-bold'

    extra = forms.CheckboxInput()

    class Meta:
        model = models.Example
        fields = [
            'some',
            'thing',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

root/management/commands/app_skeleton/views.py
# imports
import typing
from http import HTTPStatus

from django.views import View
from django.contrib import messages
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import get_user_model
from django.http.response import HttpResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required

from . import forms
from . import models

User = get_user_model()

if typing.TYPE_CHECKING:
    from django.http import HttpRequest
# End: imports -----------------------------------------------------------------


@method_decorator([login_required], name='dispatch')
class ExampleView(View):
    template = 'app_skeleton/example.html'
    form_class = forms.ExampleForm

    @permission_required('view_example')
    def get(self, request: HttpRequest, example_id: int, *args, **kwargs):
        example = get_object_or_404(models.Example, id=example_id)
        return render(request, self.template, {'example': example})

    @permission_required(['create_example', 'change_example'])
    def post(self, request: HttpRequest, example_id: int = None, *args, **kwargs):
        example = None
        if example_id:
            example = get_object_or_404(models.Example, id=example_id)
        form = self.form_class(data=request.POST, instance=example)
        if form.is_valid():
            form.save()
            messages.success(request, 'Success')
            # return redirect('index')
        return render(request, self.template, {'form': form})

    @permission_required('delete_example')
    def delete(self, request: HttpRequest, example_id: int, *args, **kwargs):
        example = get_object_or_404(models.Example, id=example_id)
        example.delete()
        return HttpResponse(status=HTTPStatus.OK)

root/templates/root/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
{% load compress %}
{% load root_tags %}
{% get_settings "ENV" as ENV %}
{% get_settings "DEV" as DEV %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- MDB (requires: .js file) -->
    <!-- Annoying wave-effect -->
    {# <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet"> #}

    <!-- Lineicons -->
    <!-- Icon library -->
    <link rel="stylesheet" href="https://cdn.lineicons.com/1.0.1/LineIcons.min.css">
    <link href="https://cdn.lineicons.com/2.0/LineIcons.css" rel="stylesheet">

    <!-- Other stylesheets -->
    {% compress css  %}
      <link rel="stylesheet" type="text/x-scss" href="{% static 'root/scss/base.scss' %}"/>
      <link rel="stylesheet" type="text/x-scss" href="{% static 'root/scss/mdb_animations.scss' %}"/>
      {% if ENV == DEV %}
      <link rel="stylesheet" type="text/x-scss" href='{% static "root/scss/dev.scss" %}'>
      {% endif %}
    {% endcompress %}
    
    <link rel="shortcut icon" type="image/png" href="{% static 'root/img/favicon-32x32.png' %}"/>


    <!-- select2 (requires: .js file) -->
    <!-- Plugin for several fields in forms -->
    {# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css" integrity="sha256-FdatTf20PQr/rWg+cAKfl6j4/IY3oohFAJ7gVC3M34E=" crossorigin="anonymous" /> #}

    <!-- TinyMCE (requires: .js file and init-script) -->
    <!-- Plugin for complex input-textfields -->
    {# <script src="https://cdn.tiny.cloud/1/5fxgnl3dek8av5x5in4ke8fhqsup13fux7rshr2l91r8lgjw/tinymce/5/tinymce.min.js"></script> #}


    <!-- flatpickr (requires .js file and init-script) -->
    <!-- Plugin for calendar date-picker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.3/flatpickr.css" integrity="sha256-7vIWE+OHz3pLhuONuFqSa/Oh/YUUHFIMooHMwN1Q2bk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.3/themes/dark.css" integrity="sha256-K7VO/dYboZOIjm2us6WE3Z8P8lsfUKaUVSnYYtPg6eE=" crossorigin="anonymous" />

    <!-- Title -->
    <title>{% block title %}Base{% endblock %}</title>

    {% block head %}
        <!-- head access for extended templates -->
    {% endblock %}
</head>

<body>

    {% block navbar %}
    {% include "root/navbar.html" %}
    {% endblock %}


    <div id="content-wrapper" class="container-fluid p-1">

        <!-- Django messages -->
        <!-- https://docs.djangoproject.com/en/3.1/ref/contrib/messages/ -->
        <!--
            Yes, there is a lot of redundant code here.
            Could possibly find a better solution, but currently this allows for
            quick independant modifications for each message type
        -->
        <div class="no-print mb-2">
            {% for message in messages %}
                {% if 'success' in message.tags %}
                    <div class="p-1 bg-success text-light rounded mb-1">
                        {{ message }}
                        <i class="btn-message-remove cursor-pointer lni-cross-circle float-right pt-1"></i>
                    </div>
                {% elif 'error' in message.tags %}
                    <div class="p-1 bg-danger text-light rounded mb-1">
                        {{ message }}
                        <i class="btn-message-remove cursor-pointer lni-cross-circle float-right pt-1"></i>
                    </div>
                {% elif 'warning' in message.tags %}
                    <div class="p-1 bg-warning text-dark rounded mb-1">
                        {{ message }}
                        <i class="btn-message-remove cursor-pointer lni-cross-circle float-right pt-1"></i>
                    </div>
                {% elif 'info' in message.tags %}
                    <div class="p-1 bg-info text-light rounded mb-1">
                        {{ message }}
                        <i class="btn-message-remove cursor-pointer lni-cross-circle float-right pt-1"></i>
                    </div>
                {% elif 'debug' in message.tags %}
                    <div class="p-1 bg-primary text-light rounded mb-1">
                        {{ message }}
                        <i class="btn-message-remove cursor-pointer lni-cross-circle float-right pt-1"></i>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        {% block body %}
            <!-- Body access for extended templates -->
        {% endblock %}
    </div>


    <!--
    Position absolute enables elements to stack on top of eachother. In this case canvas behind the footer.
    w-100 sets width to 100% because position-absolute makes div display like span.
    Be sure to wrap position-absolute elements with a div that can follow normal dom flow.
    -->
    <div class="mt-5">
        <canvas class="position-absolute w-100"></canvas>
        <div class="position-absolute w-100">
            {% include "root/footer.html" %}
        </div>
    </div>



    <!-- Begin: scripts -->
    <!-- Note: Scripts and plugins are imported last because of better user experience -->


    <!-- JQuery first, then Popper.js, then Bootstrap JS -->
    {# <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script> #}
    <script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
    {# <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/cjs/popper.min.js" integrity="sha256-OH05DFHUWzr725HmuHo3pnuvUUn+TJuj8/Qz9xytFEw=" crossorigin="anonymous"></script> #}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
    {# <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> #}

    <!-- MDB (requires: .css file) -->
    {# <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script> #}

    <!-- flatpickr (requires: .css file) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.3/flatpickr.js" integrity="sha256-3soYYYidbbsrmHXTGgxeCdgMfgt6IqWjWPKfuDWduqM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.3/l10n/no.js" integrity="sha256-q8KkXT0pTTRz4uxuUW+rWQbWyg1VTAygONGTJS/QUjE=" crossorigin="anonymous"></script>

    <!-- select2 (requires: .css file) -->
    {# <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/i18n/nb.js" integrity="sha256-vw4B7p459U8eU8SfWyGnBM2YmkxrKM43V72uzVtPIHc=" crossorigin="anonymous"></script> #}

    <!-- constellation effect for footer -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.js" integrity="sha256-U+vPaw6wGRNjtBRznIBWHgpzNvNI8pRs8fQC313cxfs=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "root/js/constellation.js" %}"></script>

    <!-- BsMultiselect -->
    <!-- https://www.jqueryscript.net/form/Bootstrap-4-Multi-Select-BsMultiSelect.html -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/js/bootstrap-multiselect.js" integrity="sha256-gh5oDg46rxRDr9QF4nehk1UNULQ05EhbM9wOerElwRc=" crossorigin="anonymous"></script>
    {# <script type="text/javascript" src="https://rawgit.com/DashboardCode/BsMultiSelect/master/dist/js/BsMultiSelect.min.js"></script> #}

    {% block scripts %}
    <!-- Note: scripts access for extended templates -->
    {% endblock %}

    <!-- Begin: base script -->
    <script type="text/javascript">
        /*
        Note: '$' is short for using JQuery. Ensure that JQuery has been imported before using '$'.
        Note: Wait for ready document (meaning all elements have loaded on screen). This
        enhances user experience because visual confirmation is prioritized over functionality.
        */
        $(document).ready(function() {

            // Note: Enables user to remove Django messages on top of page
            $('.btn-message-remove').on('click', function() {
                $(this).parent().remove();
            })

            $("form [required]").addClass("border-primary");

            // Multiselect init
            $(function(){
                // $("select").bsMultiSelect();
                $("select.plugin").multiselect();
                $(".multiselect").addClass("bg-light mt-3")
            });

            // Begin: sidebar init
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });
            $('#dismiss, .overlay').on('click', function () {
                // hide sidebar
                $('#sidebar').removeClass('active');
                // hide overlay
                $('.overlay').removeClass('active');
            });
            $('#sidebarCollapse').on('click', function () {
                // open sidebar
                $('#sidebar').addClass('active');
                // fade in the overlay
                $('.overlay').addClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
            // End: sidebar
        })
    </script>

    <!-- End: scripts -->

</body>
</html>

root/templates/root/forbidden.html
{% extends 'root/base.html' %}
{% load static %}

{% block title %}Ingen tilgang{% endblock %}

{% block head %}
    <style media="screen">

    </style>
{% endblock head %}

{% block body %}
    <div class="h1">
        Stopp en halv!
    </div>
    <div class="">
        Du har ikke tilgang til dette.
        <br>
        Vennligst ta kontakt med administrator hvis du mener du burde ha denne tilgangen.
    </div>
{% endblock %}

root/templates/root/navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'root/css/navbar.css' %}"/>

<!-- Navbar -->
<nav id="nav" class="navbar navbar-expand-md bg-dark-blur fixed-top m-0 p-1">

    <a class="navbar-brand ml-2" href="{% url 'home' %}">
        <img id="logo" width="50" src='{% static "root/img/mg-150x150.png" %}' alt="">
        <span class="d-none d-sm-none d-md-inline">
            MG's internside
        </span>
    </a>

    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse mr-auto">
        <ul class="navbar-nav mr-auto ml-3">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Events
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="distance-dropdown" style="">
                    <a class="dropdown-item text-light" href="{% url 'events:all_events' %}">Alle events</a>
                    <a class="dropdown-item text-light" href="{% url 'events:add_event' %}">Opprett events</a>
                    <!--
                    <a class="dropdown-item text-light" href="">Resultater</a>
                    <a class="dropdown-item text-light" href="">Statistikk</a>
                    -->
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Wiki
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="distance-dropdown" style="">
                    <a class="dropdown-item text-light" href="{% url 'wiki:dashboard' %}">Dashboard</a>
                    <a class="dropdown-item text-light" href="{% url 'wiki:add_folder' %}">Opprett mappe</a>
                    <a class="dropdown-item text-light" href="{% url 'wiki:add_page' %}">Opprett side</a>
                    <!--
                    <a class="dropdown-item text-light" href="">Resultater</a>
                    <a class="dropdown-item text-light" href="">Statistikk</a>
                    -->
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Galleri
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="distance-dropdown" style="">
                    <a class="dropdown-item text-light" href="{% url 'gallery:all_quotations' %}">Alle sitater</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:add_quotation' %}">Legg til sitat</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:favorite_quotations' %}">Dine favoritt sitater</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:all_uploads' %}">Alle opplastninger</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:upload' %}">Last opp fil/bilde</a>
                    <!--
                    <a class="dropdown-item text-light" href="">Resultater</a>
                    <a class="dropdown-item text-light" href="">Statistikk</a>
                    -->
                </div>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto mr-4">

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'accounts:profile' %}">
                        <i class="lni-user"></i>
                        {{ user }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        <i class=""></i>
                        Logg ut
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class=""></i>
                        Logg inn
                    </a>
                </li>
            {% endif %}


        </ul>
    </div>
</nav> <!-- End: navbar -->

root/templates/root/navbar_dev.html
<!-- Navbar -->
{% load static %}
<nav style="padding: 0px 0px 0px 20px; box-shadow: 0 8px 10px -10px #010101; -webkit-box-shadow: 0 8px 10px -10px #010101; background-color: #0d0d0d;" class="navbar navbar-expand-lg navbar-dark fixed-top">

    <a style="padding: 0px; margin: 0px 50px 0px 0px" class="navbar-brand" href="{% url 'stefan:index' %}">
        <img style="padding: 0px 0px 0px 10px" width="60" src="{% static "main/Forsvarets_merke.png" %}" alt="">
        Idretten Ørland Flystasjon
    </a>



    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div id="navbar" class="collapse navbar-collapse mr-auto">
        <ul class="navbar-nav mr-auto">


            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">
                    {# <img src="https://img.icons8.com/ios/24/FFFFFF/69.png"> #}
                    {# <i class="lni-timer"></i> #}
                    <i class="lni-calendar"></i>
                    Adminpanel
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Distance
                </a>
                <div class="dropdown-menu" aria-labelledby="distance-dropdown">
                    <a class="dropdown-item" href="{% url 'distance:register' %}">Registrer økt</a>
                    <a class="dropdown-item" href="{% url 'distance:results' %}">Resultater</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'distance:register' %}">
                    {# <img src="https://img.icons8.com/ios/24/FFFFFF/69.png"> #}
                    {# <i class="lni-timer"></i> #}
                    <i class="lni-calendar"></i>
                    Registrer
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="emil-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Emil
                </a>
                <div class="dropdown-menu" aria-labelledby="emil-dropdown">
                    <a class="dropdown-item" href="{% url 'emil:register' %}">Registrer økt</a>
                    <a class="dropdown-item" href="{% url 'emil:results' %}">Resultater</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'stefan:register' %}">
                    <i class="lni-calendar"></i>
                    Stefan
                </a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">
                        <i class="lni-calendar"></i>
                        {{ user }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        <i class="lni-calendar"></i>
                        Logg ut
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class="lni-calendar"></i>
                        Logg inn
                    </a>
                </li>
            {% endif %}


        </ul>
    </div>
</nav> <!-- End: navbar -->